export const surpriseMePrompts = [
    , ' lonely tree on a barren plain.'
    , ' city skyline at dusk.'
    , ' cabin in the woods with a chimney smoke.'
    , ' sailboat in a stormy sea.'
    , ' cozy reading nook by the fireplace.'
    , ' crowded marketplace in an exotic location.'
    , ' sunset over a mountain range.'
    , ' field of wildflowers in full bloom.'
    , ' hot air balloon soaring over a landscape.'
    , ' majestic castle on a hill.'
    , ' modern cityscape with towering skyscrapers.'
    , ' rustic barn surrounded by fields.'
    , ' serene lake in the middle of a forest.'
    , ' vast desert with sand dunes.'
    , ' small village on a hillside.'
    , ' tropical island paradise with clear waters and palm trees.'
    , ' cliff overlooking a vast ocean.'
    , ' quaint cottage in a picturesque village.'
    , ' train speeding through a mountain tunnel.'
    , ' futuristic city with flying cars.'
    , ' spooky haunted house on a dark night.'
    , ' peaceful meadow with grazing animals.'
    , ' lighthouse standing tall on a rocky coast.'
    , ' futuristic spaceship soaring through the stars.'
    , ' medieval castle with a moat and drawbridge.'
    , ' majestic waterfall cascading down a mountain.'
    , ' busy airport with planes taking off and landing.'
    , ' row of colorful houses on a quiet street.'
    , ' bridge spanning a deep canyon.'
    , ' mystical forest with glowing plants and animals.'
    , ' bustling city street with people and traffic.'
    , ' rugged coastline with crashing waves.'
    , ' peaceful countryside with rolling hills and farms.'
    , ' futuristic underwater city.'
    , ' grand library filled with books.'
    , ' mysterious cave with glowing crystals.'
    , ' luxurious beach resort with white sand beaches.'
    , ' massive concert with crowds of people.'
    , ' magical garden filled with fantastical creatures.'
    , ' creepy abandoned amusement park.'
    , ' tranquil river flowing through a forest.'
    , ' busy market square in an old town.'
    , ' remote snow-covered mountain peak.'
    , ' whimsical treehouse in a giant tree.'
    , ' bustling city park with people playing and relaxing.'
    , ' rustic cabin in a snowy landscape.'
    , ' serene village on the edge of a lake.'
    , ' futuristic metropolis with towering buildings.'
    , ' vast underground cavern filled with glowing crystals.'
    , ' peaceful countryside with a winding river.'
];

